# Generated by Django 4.0.6 on 2023-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('todayDate', models.DateField(null=True)),
                ('startAmount', models.IntegerField(default=0)),
                ('totalInDelivary', models.IntegerField(default=0)),
                ('totalInPickup', models.IntegerField(default=0)),
                ('leftAmount', models.IntegerField(default=0)),
                ('totalPrice', models.IntegerField(default=0)),
            ],
        ),
    ]
