# Generated by Django 4.0.6 on 2023-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_todayamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayamount',
            name='leftAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todayamount',
            name='startAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todayamount',
            name='totalInDelivary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todayamount',
            name='totalInPickup',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='todayamount',
            name='totalPrice',
            field=models.IntegerField(null=True),
        ),
    ]
